//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SqlServer.TransactSql {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.SqlServer.TransactSql.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generates complete database script (TSQL) for Microsoft SqlServer from a simple xml-based configuration file.
        /// </summary>
        internal static string TSqlScriptGenerator_ApplicationDescription {
            get {
                return ResourceManager.GetString("TSqlScriptGenerator_ApplicationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration File Path.
        /// </summary>
        internal static string TSqlScriptGenerator_Config_File_Description {
            get {
                return ResourceManager.GetString("TSqlScriptGenerator_Config_File_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -c|--config-file&lt;optionvalue&gt;.
        /// </summary>
        internal static string TSqlScriptGenerator_Config_File_Template {
            get {
                return ResourceManager.GetString("TSqlScriptGenerator_Config_File_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sql script generator will generate a database from supplied configuration..
        /// </summary>
        internal static string TSqlScriptGenerator_GenerateCommandDescription {
            get {
                return ResourceManager.GetString("TSqlScriptGenerator_GenerateCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -?|-h|--help.
        /// </summary>
        internal static string TSqlScriptGenerator_HelpString {
            get {
                return ResourceManager.GetString("TSqlScriptGenerator_HelpString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pauses the console after database generation..
        /// </summary>
        internal static string TSqlScriptGenerator_Pause_Description {
            get {
                return ResourceManager.GetString("TSqlScriptGenerator_Pause_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to continue....
        /// </summary>
        internal static string TSqlScriptGenerator_Pause_Message {
            get {
                return ResourceManager.GetString("TSqlScriptGenerator_Pause_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -p|--pause.
        /// </summary>
        internal static string TSqlScriptGenerator_Pause_Template {
            get {
                return ResourceManager.GetString("TSqlScriptGenerator_Pause_Template", resourceCulture);
            }
        }
    }
}
